name: Auto Update -> github-automated-puller

on:
  push:
    branches:
      - main

jobs:
  restart-github-automated-puller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Send POST request to restart github-automated-puller
        run: |
          curl_response=$(curl -X POST "129.242.219.112:5000/git-webhook" -H "Content-Type: application/json" -H "X-GitHub-Event: push" --data '{"ContainerName": "github-automated-puller"}' --fail --silent --show-error)
          
          if [ $? -ne 0 ]; then
            echo ">❌ Failed to send webhook request"
            exit 1
          fi
          
          echo ">✅ Webhook request sent successfully. Response: $curl_response"
          exit 0
