name: Auto Update -> Giter-Auto

on:
  push:
    branches:
      - main

jobs:
  restart-Giter-Auto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
