name: Auto Update -> Giter-Auto

on:
  push:
    branches:
      - main

jobs:
  restart-Giter-Auto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Send POST request to restart Giter-Auto
        run: |
          curl -X POST 129.242.219.112:5000/git-webhook

